# parameters:
#   - name: TESTENV
#     displayName: Environment
#     type: string
#     default: "SIT"
#     values:
#       - DEV
#       - TST
#       - SIT
#       - UAT
#   - name: os
#     displayName: OSType
#     type: string
#     default: "WINDOWS"
#     values:
#       - ANDROID
#       - IOS
#       - WINDOWS
  # - name: devicetype
  #   displayName: DeviceType
  #   type: string
  #   default: 'REAL'
  #   values:
  #     - REAL
  #     - VIRTUAL

pool:
  vmImage: "ubuntu-latest"

trigger:
  batch: true
  branches:
    include:
      - master
      - releases/*
      - features/*
      - fix/*

schedules:
  - cron: "0 8 * * 1-5"
    displayName: Daily Morning build
    branches:
      include:
        - master

#https://docs.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops&tabs=yaml
#https://docs.microsoft.com/en-us/azure/devops/pipelines/process/resources?view=azure-devops&tabs=example#resources-pipelines
resources:
  pipelines:
    - pipeline: securitylib # Name of the pipeline resource
      project: string # project for the source; optional for current project
      source: security-lib-ci # Name of the pipeline referenced by the pipeline resource
      trigger:
        branches:
          - master

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - script: |
      npm install
    displayName: "npm install"

  #if: build.source == "schedule" && build.branch == "master", run android and ios tests in SIT
   - script: |
      npm run test -- --cucumberOpts.tagExpression "@freshwork"
    displayName: "npm run test"
